sudo: true
language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # For C++14
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
