sudo: true
language: cpp
compiler: gcc
dist: trusty

branches:
  only:
  - master
  - /blizzard_internal.*/
  except:
  - gh-pages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r/test # For C++14
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - g++-5

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - mkdir build
  - cd build
  - cmake ../
  - make

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cd $TRAVIS_BUILD_DIR && ./generate_and_deploy_doxygen.sh'
